name: DirtyServerControl
main: gri.ppt.DirtyServerControl.DirtyServerControl
version: 1.0.1
depends: [CoreProtect]
author: ppt
commands:
  dsc:
    usage: /dsc xray <name> <days>
    permission: dirtyservercontrol.antixray.use